# CodeRabbit Configuration
# AI-powered code review for pull requests

language: "en-US"

reviews:
  profile: "chill"  # Balanced review style - not too strict
  request_changes_workflow: false  # Suggest improvements, don't block PRs
  high_level_summary: true  # Provide summary of changes
  poem: false  # Skip the fun poems
  review_status: true  # Post review status

chat:
  auto_reply: true  # Automatically respond to questions

# Customize review focus based on project principles
tone_instructions: "Focus on code quality, bugs, security, performance, tests, and docs. Follow YAGNI, KISS, and defensive programming principles. Prefer small, incremental changes. Be constructive and helpful."

# File patterns to review
path_filters:
  - "!**/*.md"  # Skip markdown files (documentation)
  - "!**/CHANGELOG.md"
  - "!**/README.md"

# Auto-review settings
auto_review:
  enabled: true  # Automatically review PRs
  drafts: false  # Don't review draft PRs
  base_branches:
    - main  # Only review PRs targeting main branch
