[tool.black]
line-length = 127
target-version = ["py312"]
include = "\\.pyi?$"
extend-exclude = """
/(
    \\.eggs
  | \\.git
  | \\.hg
  | \\.mypy_cache
  | \\.tox
  | \\.venv
  | _build
  | buck-out
  | build
  | dist
  | docs
  | tests/test_python_edit.*
  | tests/test_terminal_tools.*
  | tests/test_patch_edit.*
  | tests/test_tool_handler_comprehensive.*
)/
"""

[tool.isort]
profile = "black"
line_length = 127
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
skip = [
  "tests/test_patch_edit.py",
  "tests/test_tool_handler_comprehensive.py"
]

[tool.mypy]
python_version = "3.12"
ignore_missing_imports = true
exclude = [
    "tests/test_patch_edit.py",
    "tests/test_tool_handler_comprehensive.py"
]
