version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: react-gui/Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ..:/app
      - /app/react-gui/backend/__pycache__
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=development
      - LOG_LEVEL=DEBUG
    working_dir: /app/react-gui/backend
    command: python main.py
    stdin_open: true
    tty: true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s