name: Documentation
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  docs:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python\r\n      uses: actions/setup-python@v5\r\n      with:\r\n        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install sphinx sphinx-rtd-theme
    - name: Build documentation
      run: |
        cd docs
        make html
    - name: Upload documentation\r\n       uses: actions/upload-artifact@v4\r\n      with:
        name: documentation
        path: docs/_build/html/
