name: Security Scan
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 2 * * 0'  # Weekly on Sunday at 2 AM
jobs:
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install safety bandit semgrep
        pip install -r requirements.txt
    - name: Run safety check (known vulnerabilities)
      run: safety check --json --output safety-report.json || true
    - name: Run bandit security linter
      run: bandit -r . -f json -o bandit-report.json || true
    - name: Run semgrep security scan
      run: semgrep --config=auto --json --output=semgrep-report.json . || true
    - name: Upload security reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-reports
        path: |
          safety-report.json
          bandit-report.json
          semgrep-report.json
